sudo: false

language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

before_script:
  # install composer with optimize auto loader
  - composer install -o

script:
  - ./vendor/bin/phpcs

matrix:
  fast_finish: true
